export const ErrorCodeApi = {
  "room-error-0001": "Cơ sở không tồn tại",
  "room-error-0002": "Không tìm thấy phòng nào",
  "room-error-0003": "Phòng đã tồn tại",
  "room-error-0004": "Cơ sở không tồn tại",
  "room-error-0005": "Dữ liệu không hợp lệ",
  "room-error-0006": "Số lượng phải từ 20 đến 100",
  "room-error-0007": "Tên phòng không được để trống",
  "room-error-0008": "Tên phòng phải có độ dài từ 1 trở lên và nhở hơn 255 ký tự",
  "room-error-0009": "Phòng học không tồn tại",
  "room-error-0010": "Tên phòng không được để trống",
  "room-error-0011": "Tên phòng không hợp lệ",
  "room-error-0012": "Cơ sở không tồn tại",
  "room-error-0013": "Loại phòng không tồn tại",
  "room-error-0014": "Số lượng phải từ 20 đến 100",
  "room-error-0015": "Phòng đã tồn tại trong hệ thống",
  "room-error-0016": "Phòng không tìm thấy",
  "room-error-0017": "Xóa phòng không thành công",
  "room-error-0018": "Thay đổi trạng thái không thành công",
  "room-error-0019": "Không thể xóa phòng",

  "center-error-0001": "Cơ sở không tồn tại",
  "center-error-0002": "Tên cơ sở không được để trống",
  "center-error-0003": "Tên cơ sở không hợp lệ",
  "center-error-0004": "Tên cơ sở phải từ 1 trở lên và nhỏ hơn 255 ký tự",
  "center-error-0005": "Địa chỉ đã được sử dụng",
  "center-error-0006": "Tên cơ sở đã được sử dụng",
  "center-error-0007": "Địa chỉ đã được sử dụng",
  "center-error-0008": "Tên cơ sở đã được sử dụng",
  "center-error-0009": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "center-error-0010": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "center-error-0011": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",

  "sro-error-0001": "Cơ sở không tồn tại",
  "sro-error-0002": "SRO không tồn tại",
  "sro-error-0003": "Cơ sở không tồn tại",
  "sro-error-0004": "Role không tồn tại",
  "sro-error-0005": "Số điện thoại đã tồn tại trong hệ thống",
  "sro-error-0006": "Email cá nhân này đã tồn tại trong hệ thống",
  "sro-error-0007": "Email tổ chức này đã tồn tại trong hệ thống",
  "sro-error-0008": "Tỉnh thành không tồn tại",
  "sro-error-0009": "Quận huyện không tồn tại",
  "sro-error-0010": "Phường xã không tồn tại",
  "sro-error-0011": "Giới tính không hợp lệ",
  "sro-error-0012": "Số CMND/CCCD đã tồn tại trong hệ thống",
  "sro-error-0013": "Tối thiểu 1 trường thông tin phải được nhập",
  "sro-error-0014": "Ngày cấp CMND/CCCD không hợp lệ",
  "sro-error-0015": "Số điện thoại không hợp lệ",
  "sro-error-0016": "Email cá nhân không hợp lệ",
  "sro-error-0017": "Email tổ chức không hợp lệ",
  "sro-error-0018": "Số CMND/CCCD phải có độ dài từ 9 đến 12 ký tự",
  "sro-error-0019": "Họ và tên đệm không hợp lệ",
  "sro-error-0020": "Tên không hợp lệ",
  "sro-error-0021": "SRO không tồn tại",
  "sro-error-0022": "Dữ liệu không hợp lệ",
  "sro-error-0023": "Dữ liệu không hợp lệ",
  "sro-error-0021-1": "Email cá nhân đã được sử dụng",
  "sro-error-0022-1": "Email tổ chức đã được sử dụng",
  "sro-error-0022-2": "Email cá nhân và email tổ chức không được trùng nhau",
  "sro-error-0022-3": "Ngày sinh phải nhỏ hơn ngày hiện tại",
  "sro-error-0022-4": "Ngày cấp thẻ phải nhỏ hơn ngày hiện tại",
  "sro-error-2057": "Thay đổi trạng thái không thành công",
  "sro-error-1001": "Xóa sro không thành công",

  "address-error-0001": "Không tìm thấy địa chỉ",

  "course-family-error-0001": "Các trường không được để trống",
  "course-family-error-0002": "Tên course family không hợp lệ",
  "course-family-error-0003": "Tên course family phải có độ dài từ 1 đến 255 ký tự",
  "course-family-error-0005": "Mã course family không hợp lệ",
  "course-family-error-0006": "Mã course family phải có độ dài từ 1 đến 100 ký tự",
  "course-family-error-0007": "Năm áp dụng phải lớn hơn 0",
  "course-family-error-0008": "Mã course family đã tồn tại",
  "course-family-error-0009": "Tên course family đã tồn tại",
  "course-family-error-0010": "Tên hoặc mã course family đã tồn tại",
  "course-family-error-0011": "Không thể xóa course family này",
  "course-family-error-0012": "Thay đổi trạng thái không thành công",
  "course-family-error-0013": "Xóa course family không thành công",

  "course-error-0001": "Mã khóa học đã tồn tại",
  "course-error-0002": "Mã chương trình học đã không tồn tại",
  "course-error-0003": "Tên khóa học không hợp lệ",
  "course-error-0004": "Tên khóa học phải có độ dài từ 1 đến 255 ký tự",
  "course-error-0005": "Mã khóa học không hợp lệ",
  "course-error-0006": "Mã khóa học phải có độ dài từ 1 đến 100 ký tự",
  "course-error-0007": "Số lượng kỳ học không hợp lệ",
  "course-error-0008": "Tên khoá học đã tồn tại",
  "course-error-0009": "Mã khóa học đã tồn tại",
  "course-error-0010": "Thay đổi trạng thái không thành công",
  "course-error-0011": "Xóa khóa học không thành công",

  "module-error-0001": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "module-error-0002": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "module-error-0003": "Tên module không được để trống",
  "module-error-0004": "Tên module không hợp lệ",
  "module-error-0005": "Tên module phải có độ dài từ 1 đến 255 ký tự",
  "module-error-0006": "Mã module không hợp lệ",
  "module-error-0007": "Mã module phải có độ dài từ 1 đến 100 ký tự",
  "module-error-0008": "Tên kỳ thi Ấn Độ không hợp lệ",
  "module-error-0009": "Tên kỳ thi Ấn Độ phải có độ dài từ 1 đến 255 ký tự",
  "module-error-0010": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "module-error-0011": "Loại học không hợp lệ",
  "module-error-0013": "Loại thi không hợp lệ",
  "module-error-0014": "Tên kỳ học Ấn Độ không hợp lệ",
  "module-error-0015": "Tên kỳ học Ấn Độ phải có độ dài từ 1 đến 255 ký tự",
  "module-error-0016": "Số ngày phải lớn hơn 0",
  "module-error-0017": "Số giờ phải lớn hơn 0",
  "module-error-0018": "Mã Course không tồn tại",
  "module-error-0019": "Cơ sở không tồn tại",
  "module-error-0020": "Kỳ học không tồn tại",
  "module-error-0021": "Trong kỳ này môn học đã tồn tại",
  "module-error-0022": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "module-error-0023": "Số điểm phải lớn hơn 0",
  "module-error-0024": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "module-error-0025": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "module-error-0026": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "module-error-0027": "Tên module đã tồn tại",
  "module-error-0028": "Tên module đã tồn tại",
  "module-error-0029": "Điểm thi lý thuyết không được để trống",
  "module-error-0030": "Điểm thi thực hành không được để trống",
  "module-error-0031": "Điểm thi lý thuyết và thực hành không được để trống",
  "module-error-0032": "Không thể cập nhật môn học vì môn học đã được bắt đầu",
  "module-error-0033": "Không thể xóa môn học vì môn học đã được bắt đầu",

  "teacher-error-0002": "Phải nhập it nhất 1 trường",
  "teacher-error-0003": "Thông tin giáo viên không hợp lệ",
  "teacher-error-0004": "Trùng mã thuế thu nhập cá nhân",
  "teacher-error-0005": "Số điện thoại không hợp lệ",
  "teacher-error-0006": "Email cá nhân không hợp lệ",
  "teacher-error-0007": "Email tổ chức không hợp lệ",
  "teacher-error-0008": "Số CMND/CCCD phải có độ dài từ 9 hoặc 12",
  "teacher-error-0009": "Họ và tên đệm không hợp lệ",
  "teacher-error-0010": "Tên không hợp lệ",
  "teacher-error-0011": "Giáo viên không tồn tại",
  "teacher-error-0012": "Thông tin giáo viên không hợp lệ",
  "teacher-error-0013": "Số điện thoại đã tồn tại trong hệ thống",
  "teacher-error-0014": "Email cá nhân này đã tồn tại trong hệ thống",
  "teacher-error-0015": "Email tổ chức này đã tồn tại trong hệ thống",
  "teacher-error-0016": "Số CMND/CCCD đã tồn tại trong hệ thống",
  "teacher-error-0017": "Mã số thuế phải có độ dài từ 10",
  "teacher-error-0018": "Giáo viên không tồn tại",
  "teacher-error-0051-1": "Email cá nhân đã được sử dụng",
  "teacher-error-0052-1": "Email tổ chức đã được sử dụng",
  "teacher-error-0052-2": "Email cá nhân và email tổ chức không được trùng nhau",
  "teacher-error-0052-3": "Ngày sinh phải nhỏ hơn ngày hiện tại",
  "teacher-error-0052-4": "Mức lương phải lớn hơn 0",
  "teacher-error-0052-5": "Ngày cấp thẻ phải nhỏ hơn ngày hiện tại",
  "teacher-error-2056": "Thay đổi trạng thái không thành công",
  "teacher-error-1001": "Xóa giáo viên không thành công",

  "skill-error-0001": "Tên kỹ năng không hợp lệ",
  "skill-error-0002": "Tên kỹ năng phải có độ dài từ 1 đến 255 ký tự",
  "skill-error-0003": "Tên kỹ năng đã tồn tại",
  "skill-error-0004": "Kỹ năng không tồn tại",
  "skill-error-0005": "Tên kỹ năng đã tồn tại",
  "skill-error-0006": "Lưu kỹ năng không thành công",
  "skill-error-0007": "Tên kỹ năng không được để trống",

  "teacher-skill-error-0001": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "teacher-skill-error-0002": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "teacher-skill-error-0003": "Thông tin kỹ năng không hợp lệ",

  "grade-error-0001": "Module không tồn tại",
  "grade-error-0002": "Tổng phần trăm điểm phải là 100",
  "grade-error-0003": "Thông tin điểm không hợp lệ",
  "grade-error-0004": "Module không tồn tại",
  "grade-error-0005": "Thông tin điểm không hợp lệ",
  "grade-error-0006": "Số lượng điểm từ 1 đến 10",
  "grade-error-0007": "Module không tồn tại",
  "grade-error-0008": "Không thể thêm điểm PE khi hình thức thi là TE",
  "grade-error-0009": "Không thể thêm điểm TE khi hình thức thi là PE",
  "grade-error-0010": "Module này không thi",
  "grade-error-0011": "Không thêm được điểm thi lại",
  "grade-error-0012": "Module này cần có cả điểm PE và TE",
  "grade-error-0013": "Tổng trọng số phải lớn hơn 0",
  "grade-error-0014": "Thi lý thuyết sẽ được thêm tự động",
  "grade-error-0015": "Không thể thêm điểm ",
  "grade-error-0016": "Không thể thêm cùng lúc 2 loại điểm giống nhau",
  "grade-error-0017": "Không thể cập nhật loại điểm, môn học đã được lên lịch",


  "class-error-0068": "Không thể thêm lớp học",
  "class-error-0069": "Tên lớp học chứa ký tự đặc biệt | Các ký tự cho phép: ( ) _ - ",
  "class-error-0070": "Lớp học đã tồn tại",
  "class-error-0071": "Thông tin lớp học không hợp lệ",
  "class-error-0072": "Thời gian bắt đầu phải nhỏ hơn thời gian kết thúc và thời lượng học phải từ 1 - 4 tiếng",
  "class-error-0072-1":"Giờ học phải từ 8 giờ sáng đến 10 giờ tối",
  "class-error-0073": "Ngày nhập học không thể nhỏ hơn ngày hiện tại",
  "class-error-0074": "Ngày hoàn thành không thể bằng hoặc nhỏ hơn ngày nhập học",
  "class-error-0075": "Ngày tốt nghiệp không thể nhỏ hơn ngày hoàn thành",
  "class-error-0076": "Ngày nhập học không thể nhỏ hơn ngày nhập học đã tạo",
  "class-error-0077": "Ngày sinh phải nhỏ hơn ngày hiện tại",
  "class-error-0078": "Thất bại khi ghép lớp",
  "class-error-0079": "Tổng số học viên 2 lớp không được vượt quá 100",
  "class-error-0080": "Không có học viên nào trong Lớp hiện tại",
  "class-error-0081": "Không có học viên nào trong Lớp cần ghép",
  "class-error-0082": "Không tìm thấy chương trình học",
  "class-error-0083": "Chương trình học chưa được kích hoạt vào thời điểm lớp học bắt đầu",
  "class-error-0084": "Chương trình học chưa được kích hoạt",
  "class-error-0085": "TỈnh thành không hợp lệ",
  "class-error-0086": "Quận huyện không hợp lệ",
  "class-error-0087": "Phường xã không hợp lệ",

  "student-class-error-0001": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "student-class-error-0002": "Mã số sinh viên đã tồn tại",
  "student-class-error-0003": "Email cá nhân hoặc email tổ chức, số điện thoại, số CMND/CCCD đã tồn tại",
  "student-class-error-0004": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "student-class-error-0005": "Lớp học không tồn tại",
  "student-class-error-0006": "Hệ thống đã xảy ra lỗi, vui lòng thử lại",
  "student-class-error-0007": "Học viên đã tồn tại trong lớp học",
  "student-class-error-0008": "Email cá nhân đã tồn tại",
  "student-class-error-0009": "Mã số sinh viên đã tồn tại",
  "student-class-error-0010": "Thêm học viên không thành công",
  "student-class-error-0011": "Mã số sinh viên đã tồn tại",
  "student-class-error-0012": "Không thể thêm học viên vào lớp vì lớp đã có 100 học viên",
  "student-class-error-0013": "Lớp hiện tại không có trong cơ sở",
  "student-class-error-0014": "Lớp ghép không có trong cơ sở",

  "student-error-0001": "Họ và tên đệm không đúng định dạng",
  "student-error-0002": "Tên không được chứa ký tự đặc biệt",
  "student-error-0003": "Số điện thoại cá nhân đã tồn tại",
  "student-error-0004": "Số điện thoại không đúng định dạng",
  "student-error-0004_1": "Số điện thoại liên lạc không đúng định dạng",
  "student-error-0004_2": "Số điện thoại gia đình không đúng định dạng",
  "student-error-0004_3": "Số điện thoại phụ huynh không đúng định dạng",
  "student-error-0005": "Email cá nhân đã tồn tại",
  "student-error-0006": "Email cá nhân đã thuộc về email tổ chức khác",
  "student-error-0007": "Email tổ chức đã tồn tại",
  "student-error-0008": "Email tổ chức đã thuộc về email cá nhân khác",
  "student-error-0009": "Email cá nhân và email tổ chức không được trùng nhau",
  "student-error-00010": "CCCD/CMND đã tồn tại",
  "student-error-00011": "CCCD/CMND không đúng định dạng",
  "student-error-00014": "Tỉnh không tồn tại",
  "student-error-00015": "Huyện không tồn tại",
  "student-error-00016": "Phường không tồn tại",
  "student-error-00017": "Địa chỉ không tồn tại",
  "student-error-00018": "Giới tính không tồn tại",
  "student-error-00019": "Họ và tên, email cá nhân, email tổ chức không được để trống",
  "student-error-00020": "Tình trạng phải từ 1-7",
  "student-error-00021": "Hệ thống trả về không thành công",
  "student-error-00022": "Email cá nhân không đúng định dạng",
  "student-error-00023": "Email tổ chức không đúng định dạng",
  "student-error-00024": "Mã khóa học không tồn tại hoặc chưa được kích hoạt",
  "student-error-00025": "Quan hệ với học viên không tồn tại",
  "student-error-00026": "Địa chỉ liên lạc không đúng định dạng",
  "student-error-00027": "Ngày cấp thẻ CMT/CCCD không đúng định dạng",
  "student-error-00028": "Tên trường cấp 3 không đúng định dạng",
  "student-error-00029": "Tên trường đại học không đúng định dạng",
  "student-error-00030": "Tên công ty không đúng định dạng",
  "student-error-00031": "Tên Chức vụ không đúng định dạng",
  "student-error-00032": "Địa chỉ công ty không đúng định dạng",
  "student-error-00033": "Kế hoạch phí không đúng định dạng",
  "student-error-00034": "Học bổng không đúng định dạng",
  "student-error-00035": "Mức lương không đúng định dạng",
  "student-error-00036": "Tên phụ huynh không đúng định dạng",
  "student-error-00037": "Cập nhật thông tin học viên không thành công",
  "student-error-0038": "Lớp học hiện tại không tồn tại trong cơ sở này",
  "student-error-0039": "Lớp chuyển tới không tồn tại trong cơ sở này",
  "student-error-0040": "Học viên không có trong lớp hiện tại",
  "student-error-0041": "Học viên đã tồn tại trong lớp chuyển tới",
  "student-error-0042": "Thất bại khi chuyển lớp",
  "student-error-0043": "Lớp chuyển tới đã có hơn 100 học viên",
  "student-error-0044": "Ngày sinh phải nhỏ hơn ngày hiện tại",
  "student-error-0045": "Ngày cấp thẻ CMT/CCCD phải nhỏ hơn ngày hiện tại",
  "student-error-0046": "Lỗi khi lưu trạng thái học viên",
  "student-error-0046-1": "Khoá học không có trong chương trình học của lớp học viên muốn vào",
  "student-error-0046-2": "Lớp học không có sẵn để vào",







  "class-schedule-error-0001": "Môn học không dành cho lớp này",
  "class-schedule-error-0001_1": "Giáo viên không có tại cơ sở này",
  "class-schedule-error-0001_2": "Giáo viên chưa kích hoạt tài khoản",
  "class-schedule-error-0002": "Dữ liệu không hợp lệ",
  "class-schedule-error-0003": "Môn này đã được lên lịch",
  "class-schedule-error-0004": "Số lượng buổi học phải từ 1 đến 50",
  "class-schedule-error-0005": "Ngày bắt đầu phải lớn hơn ngày hiện tại",
  "class-schedule-error-0006": "Giờ bắt đầu phải nhỏ hơn giờ kết thúc, khoảng cách là từ 1h đến 4h",
  "class-schedule-error-0006_1": "Giờ học phải từ 8h đến 22h",
  "class-schedule-error-0007": "Phòng học lý thuyết không tồn tại",
  "class-schedule-error-0007_1": "Loại phòng không phù hợp",
  "class-schedule-error-0008": "Phòng học thực hành không tồn tại",
  "class-schedule-error-0009": "Ngày này là ngày nghỉ",
  "class-schedule-error-0010": "Ngày này giáo viên đã có lịch dạy",
  "class-schedule-error-0011": "Ngày bắt đầu không phù hợp với thời gian dạy trong tuần",
  "class-schedule-error-0012": "class-schedule-error-0012",
  "class-schedule-error-0013": "class-schedule-error-0013",
  "class-schedule-error-0014": "Phòng học lý thuyết đã được sử dụng",
  "class-schedule-error-0015": "Phòng học thực hành đã được sử dụng",
  "class-schedule-error-0016": "Phòng thi đã được sử dụng",
  "class-schedule-error-0017": "Giáo viên đã có lịch dạy",
  "class-schedule-error-0018": "Lớp học chưa sẵn sàng",
  "class-schedule-error-0019": "Thời gian học trong tuần không hợp lệ",
  "class-schedule-error-0020": "Lịch học không tồn tại",
  "class-schedule-error-0021": "Lịch học không tồn tại với cơ sở này",
  "class-schedule-error-0022": "Không thể cập nhật cho lịch học đã bắt đầu",
  "class-schedule-error-0023": "Không thể cập nhật, thời điểm này đã có lịch học của môn khác",
  "class-schedule-error-0024": "Giáo viên đã có lịch dạy",
  "class-schedule-error-0025": "Phòng học đã được sử dụng",
  "class-schedule-error-0026": "Môn học này không dành cho lớp bạn chọn",
  "class-schedule-error-0027": "Lớp không tồn tại",
  "class-schedule-error-0028": "Lịch học không tồn tại",
  "class-schedule-error-0029": "Không thể xoá lịch học này",
  "class-schedule-error-0030": "Không thể bắt đầu lịch học mới khi lịch học trước đó chưa kết thúc",
  "class-schedule-error-1001": "Lớp học không có trong cơ sở",
  "class-schedule-error-1002": "Giáo viên không có trong cơ sở",
  "class-schedule-error-1003": "Giáo viên không dạy lớp học này",

  "attendance-error-0000":"Lỗi dữ liệu",
  "attendance-error-0001":"Điểm danh đã được thực hiện trong tiết này",
  "attendance-error-0002":"Tất cả học viện phải trong lớp hoặc không phải draft",
  "attendance-error-0003":"Không tìm thấy tiết học",
  "attendance-error-0004":"Không tìm thấy lịch học của lớp",
  "attendance-error-0005":"Không thể đánh điểm danh vào lúc này",


  "day-off-error-0001": "Ngày nghỉ đã có trong hệ thống",
  "day-off-error-0002": "Ngày nghỉ phải từ ngày hiện tại trở đi",
  "day-off-error-0003": "Ngày nghỉ không đúng định dạng",
  "day-off-error-0004": "Thời gian nghỉ không đúng định dạng",
  "day-off-error-0005": "Lỗi khi xoá ngày nghỉ",
  "day-off-error-0006": "Ngày nghỉ đã có trong hệ thống",  

  "student-grade-error-0000": "Không thể cập nhật trước khi môn học bắt đầu và sau 3 ngày của tiết học cuối cùng",
  "student-grade-error-0001": "Không thể cập nhật trước khi môn học bắt đầu và sau 5 ngày của tiết học cuối cùng",
  "student-grade-error-0002": "Học viên phải trong lớp học (không phải draft)",
  "student-grade-error-0003": "Loại điểm phải trong môn học",
  "student-grade-error-0004": "Điểm phải từ 0 đến 10",
  "student-grade-error-0005": "Cập nhật thất bại",
  "student-grade-error-0006": "Điểm TE và TEResit sẽ được cập nhật bởi SRO import",
  "student-grade-error-0007": "Không thể cập nhật, môn học không có bài thi",
  "student-grade-error-0008": "Điểm không nằm trong mức cho phép",
  "student-grade-error-0009": "Điểm không nằm trong mức cho phép",

  "class-status-error-0001":"Lớp học đã được ghép",
  "class-status-error-0002":"Lớp học đã được kết thúc",

  "statistic-error-0000": "Ngày bắt đầu phải trước ngày kết thúc",

  "authorize-error-0000": "Không có quyền truy cập",

  "gpa-error-1": "Lớp học không có trong cơ sở",
  "gpa-error-2": "Giáo viên không có trong cơ sở",
  "gpa-error-3": "Môn học không có trong cơ sở",
  "gpa-error-4": "Tiết học không tồn tại",
  "gpa-error-5": "Học viên không có trong lớp học này",
  "gpa-error-6": "Giáo viên đang không dạy lớp này",
  "gpa-error-7": "Bạn đã đánh giá giáo viên trong tiết học này",
  "gpa-error-8": "Thêm đánh giá thất bại",
  "gpa-error-9": "Thêm câu trả lời đánh giá thất bại",
  "gpa-error-10": "Lớp học đang không học môn học này",
  "gpa-error-11": "Lớp học đang không học tiết học này",
  "gpa-error-12": "Giáo viên đang không dạy tiết này trong lớp",
  "gpa-error-13": "Comment phải ít hơn 1000 ký tự",
  "gpa-error-14": "Giáo viên không dạy môn này",
  "gpa-error-15": "Giáo viên không dạy môn này trong lớp này",

};
