using AcademicManagementSystem.Context.AmsModels;

namespace AcademicManagementSystemTest.MockData;

public static class StudentMockData
{
    public static readonly List<Student> Students = new List<Student>
    {
        new Student // ACTIVE
        {
            UserId = 6,
            EnrollNumber = "enrollNo 1",
            Status = 1,
            StatusDate = DateTime.Today.AddYears(-1),
            HomePhone = "0981498620",
            ContactPhone = "0981498620",
            ParentalName = "Pa",
            ParentalRelationship = "Father",
            ContactAddress = "768 ABC",
            ParentalPhone = "0981498620",
            ApplicationDate = DateTime.Today.AddYears(-1),
            ApplicationDocument = null,
            HighSchool = null,
            University = null,
            FacebookUrl = null,
            PortfolioUrl = null,
            WorkingCompany = null,
            CompanySalary = null,
            CompanyPosition = null,
            CompanyAddress = null,
            FeePlan = 0,
            Promotion = 0,
            IsDraft = false,
            CourseCode = "COURSE CODE 1"
        },
        new Student // NOT ACTIVE
        {
            UserId = 7,
            EnrollNumber = "enrollNo 2",
            Status = 1,
            StatusDate = DateTime.Today.AddYears(-1),
            HomePhone = "0981498620",
            ContactPhone = "0981498620",
            ParentalName = "Pa",
            ParentalRelationship = "Father",
            ContactAddress = "768 ABC",
            ParentalPhone = "0981498620",
            ApplicationDate = DateTime.Today.AddYears(-1),
            ApplicationDocument = null,
            HighSchool = null,
            University = null,
            FacebookUrl = null,
            PortfolioUrl = null,
            WorkingCompany = null,
            CompanySalary = null,
            CompanyPosition = null,
            CompanyAddress = null,
            FeePlan = 0,
            Promotion = 0,
            IsDraft = false,
            CourseCode = "COURSE CODE 1"
        },
        new Student // ACTIVE
        {
            UserId = 8,
            EnrollNumber = "enrollNo 3",
            Status = 1,
            StatusDate = DateTime.Today.AddYears(-1),
            HomePhone = "0981498620",
            ContactPhone = "0981498620",
            ParentalName = "Pa",
            ParentalRelationship = "Father",
            ContactAddress = "768 ABC",
            ParentalPhone = "0981498620",
            ApplicationDate = DateTime.Today.AddYears(-1),
            ApplicationDocument = null,
            HighSchool = null,
            University = null,
            FacebookUrl = null,
            PortfolioUrl = null,
            WorkingCompany = null,
            CompanySalary = null,
            CompanyPosition = null,
            CompanyAddress = null,
            FeePlan = 0,
            Promotion = 0,
            IsDraft = false,
            CourseCode = "COURSE CODE 1"
        },
        new Student // ACTIVE
        {
            UserId = 100,
            EnrollNumber = "HE100",
            Status = 1,
            StatusDate = DateTime.Today.AddYears(-1),
            HomePhone = "0111111111",
            ContactPhone = "0111111112",
            ParentalName = "Hai",
            ParentalRelationship = "Bố",
            ContactAddress = "768 ABC",
            ParentalPhone = "0111111113",
            ApplicationDate = DateTime.Today.AddYears(-1),
            ApplicationDocument = null,
            HighSchool = null,
            University = null,
            FacebookUrl = null,
            PortfolioUrl = null,
            WorkingCompany = null,
            CompanySalary = null,
            CompanyPosition = null,
            CompanyAddress = null,
            FeePlan = 0,
            Promotion = 0,
            IsDraft = false,
            CourseCode = "COURSE CODE 1"
        },
        new Student // ACTIVE
        {
            UserId = 101,
            EnrollNumber = "HE101",
            Status = 1,
            StatusDate = DateTime.Today.AddYears(-1),
            HomePhone = "0111111114",
            ContactPhone = "0111111115",
            ParentalName = "Heaz",
            ParentalRelationship = "Mẹ",
            ContactAddress = "768 ABC",
            ParentalPhone = "0111111116",
            ApplicationDate = DateTime.Today.AddYears(-1),
            ApplicationDocument = null,
            HighSchool = null,
            University = null,
            FacebookUrl = null,
            PortfolioUrl = null,
            WorkingCompany = null,
            CompanySalary = null,
            CompanyPosition = null,
            CompanyAddress = null,
            FeePlan = 0,
            Promotion = 0,
            IsDraft = false,
            CourseCode = "COURSE CODE 1"
        },
        new Student // draft and is active = false
        {
            UserId = 102,
            EnrollNumber = "HE102",
            Status = 1,
            StatusDate = DateTime.Today.AddYears(-1),
            HomePhone = "0111111117",
            ContactPhone = "0111111118",
            ParentalName = "Piace",
            ParentalRelationship = "Anh trai",
            ContactAddress = "768 ABC",
            ParentalPhone = "0111111119",
            ApplicationDate = DateTime.Today.AddYears(-1),
            ApplicationDocument = null,
            HighSchool = null,
            University = null,
            FacebookUrl = null,
            PortfolioUrl = null,
            WorkingCompany = null,
            CompanySalary = null,
            CompanyPosition = null,
            CompanyAddress = null,
            FeePlan = 0,
            Promotion = 0,
            IsDraft = true,
            CourseCode = "COURSE CODE 1"
        },
        new Student // ACTIVE
        {
            UserId = 103,
            EnrollNumber = "HE103",
            Status = 1,
            StatusDate = DateTime.Today.AddYears(-1),
            HomePhone = "0111111121",
            ContactPhone = "0111111122",
            ParentalName = "Heasdasdz",
            ParentalRelationship = "Mẹ",
            ContactAddress = "768 ABC",
            ParentalPhone = "0111111123",
            ApplicationDate = DateTime.Today.AddYears(-1),
            ApplicationDocument = null,
            HighSchool = null,
            University = null,
            FacebookUrl = null,
            PortfolioUrl = null,
            WorkingCompany = null,
            CompanySalary = null,
            CompanyPosition = null,
            CompanyAddress = null,
            FeePlan = 0,
            Promotion = 0,
            IsDraft = false,
            CourseCode = "COURSE CODE 1"
        },
    };
}