using AcademicManagementSystem.Context.AmsModels;

namespace AcademicManagementSystemTest.MockData;

public static class UserMockData
{
    public static List<User> Users = new List<User>
    {
        new User
        {
            Id = 1,
            ProvinceId = 1,
            DistrictId = 25,
            WardId = 0,
            CenterId = 1,
            GenderId = 1,
            RoleId = 1,
            FirstName = "Nguyễn Mạnh",
            LastName = "Tùng",
            Avatar = "https://photos.nmtung.dev/ams/avatar/user-id-2-20221123124123.png",
            MobilePhone = "0853576259",
            Email = "admin@nmtung.dev",
            EmailOrganization = "nmtung.study@gmail.com",
            Birthday = new DateTime(2000, 11, 13),
            CitizenIdentityCardNo = "111111111111",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 11, 13),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = true
        },
        new User // ADMIN
        {
            Id = 2,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 1,
            FirstName = "Minh",
            LastName = "Thành Admin",
            Avatar = null,
            MobilePhone = "0985563540",
            Email = "nmthanh1306@gmail.personal.com",
            EmailOrganization = "nmthanh1306@gmail.org.com",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456780",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = true
        },
        new User // SRO
        {
            Id = 3,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 2,
            FirstName = "Minh",
            LastName = "Thành SRO",
            Avatar = null,
            MobilePhone = "0985563541",
            Email = "thanhnm136@gmail.personal.com",
            EmailOrganization = "thanhnm136@gmail.org.com",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456781",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = true
        },
        new User  // TEACHER
        {
            Id = 4,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 3,
            FirstName = "Minh",
            LastName = "Thành Teacher",
            Avatar = null,
            MobilePhone = "0985563542",
            Email = "thanhnmhe141011@fpt.personal.edu.vn",
            EmailOrganization = "thanhnmhe141011@fpt.org.edu.vn",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456782",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = true,
        },
        new User // TEACHER
        {
            Id = 5,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 3,
            FirstName = "Minh",
            LastName = "Another Teacher",
            Avatar = null,
            MobilePhone = "0985563543",
            Email = "thanhnm_teacher@fpt.personal.edu.vn",
            EmailOrganization = "thanhnm_teacher@fpt.org.edu.vn",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456783",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = false
        },
        new User // STUDENT ACTIVE
        {
            Id = 6,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 4,
            FirstName = "Minh",
            LastName = "Thanh Student",
            Avatar = null,
            MobilePhone = "0985563544",
            Email = "thanhnm_student@fpt.personal.edu.vn",
            EmailOrganization = "thanhnm_student@fpt.org.edu.vn",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456784",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = true
        },
        new User // STUDENT NOT ACTIVE
        {
            Id = 7,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 4,
            FirstName = "Minh",
            LastName = "Thinh Student ",
            Avatar = null,
            MobilePhone = "0985563545",
            Email = "thanhnm_student001@fpt.personal.edu.vn",
            EmailOrganization = "thanhnm_student001@fpt.org.edu.vn",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456785",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = false
        },
        new User // STUDENT
        {
            Id = 8,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 4,
            FirstName = "Minh",
            LastName = "Another Student",
            Avatar = null,
            MobilePhone = "0985563546",
            Email = "thanhnm_student001@fpt.personal.edu.vn",
            EmailOrganization = "thanhnm_student002@fpt.org.edu.vn",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456786",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = true
        },
        new User  // TEACHER
        {
            Id = 9,
            ProvinceId = 1,
            DistrictId = 1,
            WardId = 1,
            CenterId = 1,
            GenderId = 1,
            RoleId = 3,
            FirstName = "Minh",
            LastName = "Thành Teacher",
            Avatar = null,
            MobilePhone = "0985563547",
            Email = "teacher9@fpt.personal.edu.vn",
            EmailOrganization = "teacher9@fpt.org.edu.vn",
            Birthday = new DateTime(2000, 01, 01),
            CitizenIdentityCardNo = "123456787",
            CitizenIdentityCardPublishedDate = new DateTime(2019, 01, 01),
            CitizenIdentityCardPublishedPlace = "Hà Nội",
            CreatedAt = DateTime.Now,
            UpdatedAt = DateTime.Now,
            IsActive = true,
        },
    };
}